version: '3'
services:
  database:
    image: "postgres" # use latest official postgres version
    expose:
      - "5432"
    ports:
      - "5432:5432"
    env_file:
      - database.env # configure postgres
    volumes:
      - database-data:/var/lib/postgresql/data/ # persist data even if container shuts down

  application:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - database
    links:
      - database

volumes:
  database-data: